[package]
name = "mini-browser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "mini-browser"
test = false
bench = false


[dependencies]
combine = "4.5.2"
