Copy
nodes := (node S*)*
node := element | text

text := (alphabet | digit | sign | " ")+
element := open_tag S* nodes S* close_tag

open_tag := "<" tag_name (S+ attributes)*">"
close_tag := "</" tag_name ">"

tag_name := alphabet+

attributes := (attribute S*)*
attribute := attribute_name S* "=" S* attribute_value

attribute_name := alphabet+
attribute_value := '"' attribute_inner_value '"'
attribute_inner_value := (alphabet | digit | sign | " ")+

alphabet = "a" | "b" | "c" | "d" | "e" | "f" | "g" | "h" | "i" | "j" | "k" | "l" | "m" | "n" | "o" | "p" | "q" | "r" | "s" | "t" | "u" | "v" | "w" | "x" | "y" | "z" | "A" | "B" | "C" | "D" | "E" | "F" | "G" | "H" | "I" | "J" | "K" | "L" | "M" | "N" | "O" | "P" | "Q" | "R" | "S" | "T" | "U" | "V" | "W" | "X" | "Y" | "Z"
digit = "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9"
sign = "[" | "]" | "." | "{" | "}" | ":" | ";" | "\\" | "`" | "'" | "(" | ")"
S := " " | "\n"
